"use strict";
const { requireAdmin } = require("../../server/admin-lib");
const ASSET_VERSION = String(process.env.VERCEL_GIT_COMMIT_SHA || process.env.VERCEL_DEPLOYMENT_ID || "current").replace(/[^a-zA-Z0-9_-]/g, "").slice(0, 64) || "current";
module.exports = async function handler(req, res) {
  res.setHeader("Cache-Control", "no-store");
  res.setHeader("X-Robots-Tag", "noindex, nofollow");
  res.setHeader("Content-Security-Policy", "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' https://res.cloudinary.com https://autohaus.bg https://ajoiqomflplhadyhxvfe.supabase.co blob: data:; connect-src 'self' https://ajoiqomflplhadyhxvfe.supabase.co https://ajoiqomflplhadyhxvfe.storage.supabase.co; base-uri 'self'; frame-ancestors 'none'; form-action 'self'");
  if (req.method !== "GET") { res.statusCode = 405; res.setHeader("Allow", "GET"); res.end("Method not allowed"); return; }
  const user = await requireAdmin(req, res);
  if (!user) { res.statusCode = 302; res.setHeader("Location", "/admin/login.html"); res.end(); return; }
  res.statusCode = 200;
  res.setHeader("Content-Type", "text/html; charset=utf-8");
  res.end(`<!doctype html><html lang="bg"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="robots" content="noindex,nofollow"><meta name="theme-color" content="#17191a"><title>AutoHaus Admin</title><link rel="icon" href="/favicon.jpg"><link rel="stylesheet" href="/admin/admin.css?v=${ASSET_VERSION}"><link rel="stylesheet" href="/admin/image-sorter.css?v=${ASSET_VERSION}"><style>.field-grid{align-items:start}</style><script defer src="/admin/image-sorter.js?v=${ASSET_VERSION}"></script><script defer src="/admin/notes-translation.js?v=${ASSET_VERSION}"></script><script defer src="/admin/admin-fixes.js?v=${ASSET_VERSION}"></script><script defer src="/admin/admin.js?v=${ASSET_VERSION}"></script><script defer src="/admin/advanced.js?v=${ASSET_VERSION}"></script></head><body class="ah-admin" data-admin-user="${escapeHtml(user.id)}" data-admin-role="${escapeHtml(user.adminRole)}"><a class="skip-link" href="#admin-view" data-bg="Към съдържанието" data-en="Skip to content">Към съдържанието</a><div class="app-shell"><button type="button" id="menu-backdrop" class="menu-backdrop" aria-label="Close menu" hidden></button><aside class="side" id="admin-navigation"><a class="side__brand" href="/admin" aria-label="AutoHaus Admin"><img src="/autohaus.svg" width="482" height="85" alt="AutoHaus"><span class="side__brand-tag">ADMIN</span></a><nav class="side__nav" aria-label="Admin"><button type="button" data-route="dashboard" data-bg="Начало" data-en="Overview">Начало</button><button type="button" data-route="cars" data-bg="Автомобили" data-en="Cars">Автомобили</button><button type="button" data-route="new" data-bg="+ Добави автомобил" data-en="+ Add car">+ Добави автомобил</button><button type="button" data-route="settings" data-bg="Настройки" data-en="Settings">Настройки</button></nav><div class="side__foot"><a class="site-link" href="/" target="_blank" rel="noopener" data-bg="Виж сайта ↗" data-en="View website ↗">Виж сайта ↗</a><span class="side__user">${escapeHtml(user.email)}</span><button type="button" id="logout" data-bg="Изход" data-en="Sign out">Изход</button></div></aside><header class="mobile-head"><a href="/admin" aria-label="AutoHaus Admin"><img src="/autohaus.svg" width="482" height="85" alt="AutoHaus"><span class="mobile-brand__tag">ADMIN</span></a><button type="button" id="mobile-menu" aria-controls="admin-navigation" aria-expanded="false" data-bg="Меню" data-en="Menu">Меню</button></header><main class="workspace"><div id="auth-notice" class="auth-notice" role="alert" hidden></div><div id="admin-view" class="view" tabindex="-1"></div></main></div><div class="toast" id="toast" role="status" aria-live="polite"></div></body></html>`);
};
function escapeHtml(value) { return String(value || "").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;"); }
